service:
  name: podinfoservice
  identifier: podinfoservice
  orgIdentifier: default
  projectIdentifier: Femi_Awe
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: configjson
            type: ReleaseRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: githubconnector
                  gitFetchType: Branch
                  paths:
                    - configs/git-generator-files-discovery/cluster-config/engineering/<+env.name>/config.json
                  branch: main
        - manifest:
            identifier: podinfodeployment
            type: DeploymentRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: githubconnector
                  gitFetchType: Branch
                  paths:
                    - configs/git-generator-files-discovery/git-generator-files.yaml
                  branch: main
    type: Kubernetes
  gitOpsEnabled: true
